steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/user-api:$SHORT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/user-api:$SHORT_SHA"]
# - name: 'gcr.io/cloud-builders/gke-deploy'
#   args:
#   - run
#   - --filename=[CONFIG]
#   - --image=gcr.io/$PROJECT_ID/user-api:latest
#   - --location=[LOCATION]
#   - --cluster=[CLUSTER]