steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/user-api:$SHORT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/$PROJECT_ID/user-api:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/gke-deploy'
  args:
  - run
  - --filename=k8s/deploy.yml
  - --image=gcr.io/$PROJECT_ID/user-api:$SHORT_SHA
  - --location=us-central1-a
  - --cluster=standard-cluster-1