apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: user-api-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: davidjohnmac/user-api
        ports:
        - containerPort: 3000
