apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: user-api-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-api
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: user-api
        image: davidjohnmac/user-api:0.0.2
        ports:
        - containerPort: 3000