apiVersion: v1
kind: Service
metadata:
  name: user-api-svc
  labels:
    app: user-api
spec:
  type: NodePort
  ports:
  - port: 30000
    nodePort: 30000
    targetPort: 3000
    protocol: TCP
  selector:
    app: user-api